### ISSUE TITLE
Maybe we can generate for only one folder and opt in

### ISSUE THREAD

**Issue by sm-riyadh** [normidar/auto_exporter#6]
We can maybe search for files which have the annotation 'auto_export' and then only exports the files in that folder

**Comment by normidar** [comment]
@sm-riyadh 
Thanks for your comment

It depends on whether we need to export a small or large amount of code.

If you only export a small number of files, I think we could create another library for this.

Because some people wanted to exclude some files(see #1), I think they exported most of the code.

**Comment by normidar** [comment]
Maybe we can predefined some settings that user can switch it on yaml file.

I think this is a good idea.

@sm-riyadh 
what about this?

**Comment by normidar** [comment]
like freezed: https://github.com/rrousselGit/freezed/tree/master?tab=readme-ov-file#changing-the-behavior-for-the-entire-project

**Comment by normidar** [comment]
we will release this feature on v3.0.0 !

**Comment by normidar** [comment]
adding a AutoExport annotation...

**Comment by normidar** [comment]
@sm-riyadh 

Done, you can use `@AutoExport()` after 3.0.0, but you should add some settings to `build.yaml` file.

See the `README.md`
